version: '3'

# TODO: add services for each backend and forntend !

services:
  db:
    container_name: transcendence-db
    image: postgres
    restart: on-failure
    env_file: "backend/.env"
    ports:
      - "3030:5432" # TODO: change port in production!
  redis:
    container_name: transcendence-redis
    image: redis
    restart: on-failure
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file: "backend/.env"
    ports:
      - "6379:6379"

# TODO: add volume for db & redis